package romannumerals

// Source: exercism/problem-specifications
// Commit: b820099 Allow prettier to format more files (#1966)

type romanNumeralTest struct {
	description string
	input       int
	expected    string
	expectError bool // false for all autogenerated test cases
}

var validRomanNumeralTests = []romanNumeralTest{
	{
		description: "1 is I",
		input:       1,
		expected:    "I",
		expectError: false,
	},
	{
		description: "2 is II",
		input:       2,
		expected:    "II",
		expectError: false,
	},
	{
		description: "3 is III",
		input:       3,
		expected:    "III",
		expectError: false,
	},
	{
		description: "4 is IV",
		input:       4,
		expected:    "IV",
		expectError: false,
	},
	{
		description: "5 is V",
		input:       5,
		expected:    "V",
		expectError: false,
	},
	{
		description: "6 is VI",
		input:       6,
		expected:    "VI",
		expectError: false,
	},
	{
		description: "9 is IX",
		input:       9,
		expected:    "IX",
		expectError: false,
	},
	{
		description: "27 is XXVII",
		input:       27,
		expected:    "XXVII",
		expectError: false,
	},
	{
		description: "48 is XLVIII",
		input:       48,
		expected:    "XLVIII",
		expectError: false,
	},
	{
		description: "49 is XLIX",
		input:       49,
		expected:    "XLIX",
		expectError: false,
	},
	{
		description: "59 is LIX",
		input:       59,
		expected:    "LIX",
		expectError: false,
	},
	{
		description: "93 is XCIII",
		input:       93,
		expected:    "XCIII",
		expectError: false,
	},
	{
		description: "141 is CXLI",
		input:       141,
		expected:    "CXLI",
		expectError: false,
	},
	{
		description: "163 is CLXIII",
		input:       163,
		expected:    "CLXIII",
		expectError: false,
	},
	{
		description: "402 is CDII",
		input:       402,
		expected:    "CDII",
		expectError: false,
	},
	{
		description: "575 is DLXXV",
		input:       575,
		expected:    "DLXXV",
		expectError: false,
	},
	{
		description: "911 is CMXI",
		input:       911,
		expected:    "CMXI",
		expectError: false,
	},
	{
		description: "1024 is MXXIV",
		input:       1024,
		expected:    "MXXIV",
		expectError: false,
	},
	{
		description: "3000 is MMM",
		input:       3000,
		expected:    "MMM",
		expectError: false,
	},
	{
		description: "16 is XVI",
		input:       16,
		expected:    "XVI",
		expectError: false,
	},
	{
		description: "66 is LXVI",
		input:       66,
		expected:    "LXVI",
		expectError: false,
	},
	{
		description: "166 is CLXVI",
		input:       166,
		expected:    "CLXVI",
		expectError: false,
	},
	{
		description: "666 is DCLXVI",
		input:       666,
		expected:    "DCLXVI",
		expectError: false,
	},
	{
		description: "1666 is MDCLXVI",
		input:       1666,
		expected:    "MDCLXVI",
		expectError: false,
	},
}
