run:
  timeout: 8m
linters:
  disable-all: true
  enable:
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - gofmt
    - gosec
    - gosimple
    - govet
    - staticcheck
linters-settings:
  gocritic:
    disabled-checks:
      - yodaStyleExpr
    enabled-tags:
      - diagnostic
      - style
      - performance
      - opinionated
    settings:
      hugeParam:
        sizeThreshold: 384
      rangeValCopy:
        sizeThreshold: 384
  gofmt:
    simplify: true
  gosec:
    excludes:
      - G404 # Insecure random number source (rand)
