package meetup

// This is an auto-generated file. Do not change it manually. Run the generator to update the file.
// See https://github.com/exercism/go#synchronizing-tests-and-instructions
// Source: exercism/problem-specifications
// Commit: 37f7831 meetup: improve descriptions by saying why each case is tested (#1919)

import "time"

var testCases = []struct {
	description string
	year        int
	month       time.Month
	week        WeekSchedule
	weekday     time.Weekday
	expectedDay int
}{
	{
		description: "when teenth Monday is the 13th, the first day of the teenth week",
		year:        2013,
		month:       5,
		week:        Teenth,
		weekday:     time.Monday,
		expectedDay: 13,
	},
	{
		description: "when teenth Monday is the 19th, the last day of the teenth week",
		year:        2013,
		month:       8,
		week:        Teenth,
		weekday:     time.Monday,
		expectedDay: 19,
	},
	{
		description: "when teenth Monday is some day in the middle of the teenth week",
		year:        2013,
		month:       9,
		week:        Teenth,
		weekday:     time.Monday,
		expectedDay: 16,
	},
	{
		description: "when teenth Tuesday is the 19th, the last day of the teenth week",
		year:        2013,
		month:       3,
		week:        Teenth,
		weekday:     time.Tuesday,
		expectedDay: 19,
	},
	{
		description: "when teenth Tuesday is some day in the middle of the teenth week",
		year:        2013,
		month:       4,
		week:        Teenth,
		weekday:     time.Tuesday,
		expectedDay: 16,
	},
	{
		description: "when teenth Tuesday is the 13th, the first day of the teenth week",
		year:        2013,
		month:       8,
		week:        Teenth,
		weekday:     time.Tuesday,
		expectedDay: 13,
	},
	{
		description: "when teenth Wednesday is some day in the middle of the teenth week",
		year:        2013,
		month:       1,
		week:        Teenth,
		weekday:     time.Wednesday,
		expectedDay: 16,
	},
	{
		description: "when teenth Wednesday is the 13th, the first day of the teenth week",
		year:        2013,
		month:       2,
		week:        Teenth,
		weekday:     time.Wednesday,
		expectedDay: 13,
	},
	{
		description: "when teenth Wednesday is the 19th, the last day of the teenth week",
		year:        2013,
		month:       6,
		week:        Teenth,
		weekday:     time.Wednesday,
		expectedDay: 19,
	},
	{
		description: "when teenth Thursday is some day in the middle of the teenth week",
		year:        2013,
		month:       5,
		week:        Teenth,
		weekday:     time.Thursday,
		expectedDay: 16,
	},
	{
		description: "when teenth Thursday is the 13th, the first day of the teenth week",
		year:        2013,
		month:       6,
		week:        Teenth,
		weekday:     time.Thursday,
		expectedDay: 13,
	},
	{
		description: "when teenth Thursday is the 19th, the last day of the teenth week",
		year:        2013,
		month:       9,
		week:        Teenth,
		weekday:     time.Thursday,
		expectedDay: 19,
	},
	{
		description: "when teenth Friday is the 19th, the last day of the teenth week",
		year:        2013,
		month:       4,
		week:        Teenth,
		weekday:     time.Friday,
		expectedDay: 19,
	},
	{
		description: "when teenth Friday is some day in the middle of the teenth week",
		year:        2013,
		month:       8,
		week:        Teenth,
		weekday:     time.Friday,
		expectedDay: 16,
	},
	{
		description: "when teenth Friday is the 13th, the first day of the teenth week",
		year:        2013,
		month:       9,
		week:        Teenth,
		weekday:     time.Friday,
		expectedDay: 13,
	},
	{
		description: "when teenth Saturday is some day in the middle of the teenth week",
		year:        2013,
		month:       2,
		week:        Teenth,
		weekday:     time.Saturday,
		expectedDay: 16,
	},
	{
		description: "when teenth Saturday is the 13th, the first day of the teenth week",
		year:        2013,
		month:       4,
		week:        Teenth,
		weekday:     time.Saturday,
		expectedDay: 13,
	},
	{
		description: "when teenth Saturday is the 19th, the last day of the teenth week",
		year:        2013,
		month:       10,
		week:        Teenth,
		weekday:     time.Saturday,
		expectedDay: 19,
	},
	{
		description: "when teenth Sunday is the 19th, the last day of the teenth week",
		year:        2013,
		month:       5,
		week:        Teenth,
		weekday:     time.Sunday,
		expectedDay: 19,
	},
	{
		description: "when teenth Sunday is some day in the middle of the teenth week",
		year:        2013,
		month:       6,
		week:        Teenth,
		weekday:     time.Sunday,
		expectedDay: 16,
	},
	{
		description: "when teenth Sunday is the 13th, the first day of the teenth week",
		year:        2013,
		month:       10,
		week:        Teenth,
		weekday:     time.Sunday,
		expectedDay: 13,
	},
	{
		description: "when first Monday is some day in the middle of the first week",
		year:        2013,
		month:       3,
		week:        First,
		weekday:     time.Monday,
		expectedDay: 4,
	},
	{
		description: "when first Monday is the 1st, the first day of the first week",
		year:        2013,
		month:       4,
		week:        First,
		weekday:     time.Monday,
		expectedDay: 1,
	},
	{
		description: "when first Tuesday is the 7th, the last day of the first week",
		year:        2013,
		month:       5,
		week:        First,
		weekday:     time.Tuesday,
		expectedDay: 7,
	},
	{
		description: "when first Tuesday is some day in the middle of the first week",
		year:        2013,
		month:       6,
		week:        First,
		weekday:     time.Tuesday,
		expectedDay: 4,
	},
	{
		description: "when first Wednesday is some day in the middle of the first week",
		year:        2013,
		month:       7,
		week:        First,
		weekday:     time.Wednesday,
		expectedDay: 3,
	},
	{
		description: "when first Wednesday is the 7th, the last day of the first week",
		year:        2013,
		month:       8,
		week:        First,
		weekday:     time.Wednesday,
		expectedDay: 7,
	},
	{
		description: "when first Thursday is some day in the middle of the first week",
		year:        2013,
		month:       9,
		week:        First,
		weekday:     time.Thursday,
		expectedDay: 5,
	},
	{
		description: "when first Thursday is another day in the middle of the first week",
		year:        2013,
		month:       10,
		week:        First,
		weekday:     time.Thursday,
		expectedDay: 3,
	},
	{
		description: "when first Friday is the 1st, the first day of the first week",
		year:        2013,
		month:       11,
		week:        First,
		weekday:     time.Friday,
		expectedDay: 1,
	},
	{
		description: "when first Friday is some day in the middle of the first week",
		year:        2013,
		month:       12,
		week:        First,
		weekday:     time.Friday,
		expectedDay: 6,
	},
	{
		description: "when first Saturday is some day in the middle of the first week",
		year:        2013,
		month:       1,
		week:        First,
		weekday:     time.Saturday,
		expectedDay: 5,
	},
	{
		description: "when first Saturday is another day in the middle of the first week",
		year:        2013,
		month:       2,
		week:        First,
		weekday:     time.Saturday,
		expectedDay: 2,
	},
	{
		description: "when first Sunday is some day in the middle of the first week",
		year:        2013,
		month:       3,
		week:        First,
		weekday:     time.Sunday,
		expectedDay: 3,
	},
	{
		description: "when first Sunday is the 7th, the last day of the first week",
		year:        2013,
		month:       4,
		week:        First,
		weekday:     time.Sunday,
		expectedDay: 7,
	},
	{
		description: "when second Monday is some day in the middle of the second week",
		year:        2013,
		month:       3,
		week:        Second,
		weekday:     time.Monday,
		expectedDay: 11,
	},
	{
		description: "when second Monday is the 8th, the first day of the second week",
		year:        2013,
		month:       4,
		week:        Second,
		weekday:     time.Monday,
		expectedDay: 8,
	},
	{
		description: "when second Tuesday is the 14th, the last day of the second week",
		year:        2013,
		month:       5,
		week:        Second,
		weekday:     time.Tuesday,
		expectedDay: 14,
	},
	{
		description: "when second Tuesday is some day in the middle of the second week",
		year:        2013,
		month:       6,
		week:        Second,
		weekday:     time.Tuesday,
		expectedDay: 11,
	},
	{
		description: "when second Wednesday is some day in the middle of the second week",
		year:        2013,
		month:       7,
		week:        Second,
		weekday:     time.Wednesday,
		expectedDay: 10,
	},
	{
		description: "when second Wednesday is the 14th, the last day of the second week",
		year:        2013,
		month:       8,
		week:        Second,
		weekday:     time.Wednesday,
		expectedDay: 14,
	},
	{
		description: "when second Thursday is some day in the middle of the second week",
		year:        2013,
		month:       9,
		week:        Second,
		weekday:     time.Thursday,
		expectedDay: 12,
	},
	{
		description: "when second Thursday is another day in the middle of the second week",
		year:        2013,
		month:       10,
		week:        Second,
		weekday:     time.Thursday,
		expectedDay: 10,
	},
	{
		description: "when second Friday is the 8th, the first day of the second week",
		year:        2013,
		month:       11,
		week:        Second,
		weekday:     time.Friday,
		expectedDay: 8,
	},
	{
		description: "when second Friday is some day in the middle of the second week",
		year:        2013,
		month:       12,
		week:        Second,
		weekday:     time.Friday,
		expectedDay: 13,
	},
	{
		description: "when second Saturday is some day in the middle of the second week",
		year:        2013,
		month:       1,
		week:        Second,
		weekday:     time.Saturday,
		expectedDay: 12,
	},
	{
		description: "when second Saturday is another day in the middle of the second week",
		year:        2013,
		month:       2,
		week:        Second,
		weekday:     time.Saturday,
		expectedDay: 9,
	},
	{
		description: "when second Sunday is some day in the middle of the second week",
		year:        2013,
		month:       3,
		week:        Second,
		weekday:     time.Sunday,
		expectedDay: 10,
	},
	{
		description: "when second Sunday is the 14th, the last day of the second week",
		year:        2013,
		month:       4,
		week:        Second,
		weekday:     time.Sunday,
		expectedDay: 14,
	},
	{
		description: "when third Monday is some day in the middle of the third week",
		year:        2013,
		month:       3,
		week:        Third,
		weekday:     time.Monday,
		expectedDay: 18,
	},
	{
		description: "when third Monday is the 15th, the first day of the third week",
		year:        2013,
		month:       4,
		week:        Third,
		weekday:     time.Monday,
		expectedDay: 15,
	},
	{
		description: "when third Tuesday is the 21st, the last day of the third week",
		year:        2013,
		month:       5,
		week:        Third,
		weekday:     time.Tuesday,
		expectedDay: 21,
	},
	{
		description: "when third Tuesday is some day in the middle of the third week",
		year:        2013,
		month:       6,
		week:        Third,
		weekday:     time.Tuesday,
		expectedDay: 18,
	},
	{
		description: "when third Wednesday is some day in the middle of the third week",
		year:        2013,
		month:       7,
		week:        Third,
		weekday:     time.Wednesday,
		expectedDay: 17,
	},
	{
		description: "when third Wednesday is the 21st, the last day of the third week",
		year:        2013,
		month:       8,
		week:        Third,
		weekday:     time.Wednesday,
		expectedDay: 21,
	},
	{
		description: "when third Thursday is some day in the middle of the third week",
		year:        2013,
		month:       9,
		week:        Third,
		weekday:     time.Thursday,
		expectedDay: 19,
	},
	{
		description: "when third Thursday is another day in the middle of the third week",
		year:        2013,
		month:       10,
		week:        Third,
		weekday:     time.Thursday,
		expectedDay: 17,
	},
	{
		description: "when third Friday is the 15th, the first day of the third week",
		year:        2013,
		month:       11,
		week:        Third,
		weekday:     time.Friday,
		expectedDay: 15,
	},
	{
		description: "when third Friday is some day in the middle of the third week",
		year:        2013,
		month:       12,
		week:        Third,
		weekday:     time.Friday,
		expectedDay: 20,
	},
	{
		description: "when third Saturday is some day in the middle of the third week",
		year:        2013,
		month:       1,
		week:        Third,
		weekday:     time.Saturday,
		expectedDay: 19,
	},
	{
		description: "when third Saturday is another day in the middle of the third week",
		year:        2013,
		month:       2,
		week:        Third,
		weekday:     time.Saturday,
		expectedDay: 16,
	},
	{
		description: "when third Sunday is some day in the middle of the third week",
		year:        2013,
		month:       3,
		week:        Third,
		weekday:     time.Sunday,
		expectedDay: 17,
	},
	{
		description: "when third Sunday is the 21st, the last day of the third week",
		year:        2013,
		month:       4,
		week:        Third,
		weekday:     time.Sunday,
		expectedDay: 21,
	},
	{
		description: "when fourth Monday is some day in the middle of the fourth week",
		year:        2013,
		month:       3,
		week:        Fourth,
		weekday:     time.Monday,
		expectedDay: 25,
	},
	{
		description: "when fourth Monday is the 22nd, the first day of the fourth week",
		year:        2013,
		month:       4,
		week:        Fourth,
		weekday:     time.Monday,
		expectedDay: 22,
	},
	{
		description: "when fourth Tuesday is the 28th, the last day of the fourth week",
		year:        2013,
		month:       5,
		week:        Fourth,
		weekday:     time.Tuesday,
		expectedDay: 28,
	},
	{
		description: "when fourth Tuesday is some day in the middle of the fourth week",
		year:        2013,
		month:       6,
		week:        Fourth,
		weekday:     time.Tuesday,
		expectedDay: 25,
	},
	{
		description: "when fourth Wednesday is some day in the middle of the fourth week",
		year:        2013,
		month:       7,
		week:        Fourth,
		weekday:     time.Wednesday,
		expectedDay: 24,
	},
	{
		description: "when fourth Wednesday is the 28th, the last day of the fourth week",
		year:        2013,
		month:       8,
		week:        Fourth,
		weekday:     time.Wednesday,
		expectedDay: 28,
	},
	{
		description: "when fourth Thursday is some day in the middle of the fourth week",
		year:        2013,
		month:       9,
		week:        Fourth,
		weekday:     time.Thursday,
		expectedDay: 26,
	},
	{
		description: "when fourth Thursday is another day in the middle of the fourth week",
		year:        2013,
		month:       10,
		week:        Fourth,
		weekday:     time.Thursday,
		expectedDay: 24,
	},
	{
		description: "when fourth Friday is the 22nd, the first day of the fourth week",
		year:        2013,
		month:       11,
		week:        Fourth,
		weekday:     time.Friday,
		expectedDay: 22,
	},
	{
		description: "when fourth Friday is some day in the middle of the fourth week",
		year:        2013,
		month:       12,
		week:        Fourth,
		weekday:     time.Friday,
		expectedDay: 27,
	},
	{
		description: "when fourth Saturday is some day in the middle of the fourth week",
		year:        2013,
		month:       1,
		week:        Fourth,
		weekday:     time.Saturday,
		expectedDay: 26,
	},
	{
		description: "when fourth Saturday is another day in the middle of the fourth week",
		year:        2013,
		month:       2,
		week:        Fourth,
		weekday:     time.Saturday,
		expectedDay: 23,
	},
	{
		description: "when fourth Sunday is some day in the middle of the fourth week",
		year:        2013,
		month:       3,
		week:        Fourth,
		weekday:     time.Sunday,
		expectedDay: 24,
	},
	{
		description: "when fourth Sunday is the 28th, the last day of the fourth week",
		year:        2013,
		month:       4,
		week:        Fourth,
		weekday:     time.Sunday,
		expectedDay: 28,
	},
	{
		description: "last Monday in a month with four Mondays",
		year:        2013,
		month:       3,
		week:        Last,
		weekday:     time.Monday,
		expectedDay: 25,
	},
	{
		description: "last Monday in a month with five Mondays",
		year:        2013,
		month:       4,
		week:        Last,
		weekday:     time.Monday,
		expectedDay: 29,
	},
	{
		description: "last Tuesday in a month with four Tuesdays",
		year:        2013,
		month:       5,
		week:        Last,
		weekday:     time.Tuesday,
		expectedDay: 28,
	},
	{
		description: "last Tuesday in another month with four Tuesdays",
		year:        2013,
		month:       6,
		week:        Last,
		weekday:     time.Tuesday,
		expectedDay: 25,
	},
	{
		description: "last Wednesday in a month with five Wednesdays",
		year:        2013,
		month:       7,
		week:        Last,
		weekday:     time.Wednesday,
		expectedDay: 31,
	},
	{
		description: "last Wednesday in a month with four Wednesdays",
		year:        2013,
		month:       8,
		week:        Last,
		weekday:     time.Wednesday,
		expectedDay: 28,
	},
	{
		description: "last Thursday in a month with four Thursdays",
		year:        2013,
		month:       9,
		week:        Last,
		weekday:     time.Thursday,
		expectedDay: 26,
	},
	{
		description: "last Thursday in a month with five Thursdays",
		year:        2013,
		month:       10,
		week:        Last,
		weekday:     time.Thursday,
		expectedDay: 31,
	},
	{
		description: "last Friday in a month with five Fridays",
		year:        2013,
		month:       11,
		week:        Last,
		weekday:     time.Friday,
		expectedDay: 29,
	},
	{
		description: "last Friday in a month with four Fridays",
		year:        2013,
		month:       12,
		week:        Last,
		weekday:     time.Friday,
		expectedDay: 27,
	},
	{
		description: "last Saturday in a month with four Saturdays",
		year:        2013,
		month:       1,
		week:        Last,
		weekday:     time.Saturday,
		expectedDay: 26,
	},
	{
		description: "last Saturday in another month with four Saturdays",
		year:        2013,
		month:       2,
		week:        Last,
		weekday:     time.Saturday,
		expectedDay: 23,
	},
	{
		description: "last Sunday in a month with five Sundays",
		year:        2013,
		month:       3,
		week:        Last,
		weekday:     time.Sunday,
		expectedDay: 31,
	},
	{
		description: "last Sunday in a month with four Sundays",
		year:        2013,
		month:       4,
		week:        Last,
		weekday:     time.Sunday,
		expectedDay: 28,
	},
	{
		description: "when last Wednesday in February in a leap year is the 29th",
		year:        2012,
		month:       2,
		week:        Last,
		weekday:     time.Wednesday,
		expectedDay: 29,
	},
	{
		description: "last Wednesday in December that is also the last day of the year",
		year:        2014,
		month:       12,
		week:        Last,
		weekday:     time.Wednesday,
		expectedDay: 31,
	},
	{
		description: "when last Sunday in February in a non-leap year is not the 29th",
		year:        2015,
		month:       2,
		week:        Last,
		weekday:     time.Sunday,
		expectedDay: 22,
	},
	{
		description: "when first Friday is the 7th, the last day of the first week",
		year:        2012,
		month:       12,
		week:        First,
		weekday:     time.Friday,
		expectedDay: 7,
	},
}
