name: gotools check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: gotools check
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version: 1.26

      - name: Check go.mod files
        shell: bash
        run: |
          cd gotools
          go run main.go gomod
