name: PR Comment

on: [pull_request_target]

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: exercism/pr-commenter-action@19121db03822c22d1dd4e74f0b9b733688e067c5
        with:
          github-token: '${{ github.token }}'
          config-file: '.github/pr-commenter.yml'
          template-variables: |
            {
              "prAuthor": "${{ github.event.pull_request.user.login }}"
            }
